services:
  website_api:
    image: nongdev/node-backend:latest
    restart: always
    networks:
      - web   # connect to global Caddy network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend_website:
    build:
      context: ./frontend
    image: nongdev/frontend_website:latest
    restart: always
    networks:
      - web

networks:
  web:
    external: true
