version: "3.8"

services:
  vue-app:
    build: .
    container_name: vue-caddy
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
    restart: always
    volumes:
      - ./dist:/usr/share/caddy    # Vue build output
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data           # Caddy data (certs)
      - caddy_config:/config       # Caddy config

volumes:
  caddy_data:
  caddy_config:
