
services:
  website_api:
    image: nongdev/node-backend:latest
    restart: always
    ports:
      - "9090:9090"  # optional, if you want host access
    networks:
      - my-net

  web:
    image: nongdev/vue-caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - my-net

networks:
  my-net:

volumes:
  caddy_data:
  caddy_config: